package enums;

public enum Day_ {

    // ENUM IS NOT A CLASS. ENUM VARIABLE ARE CONSTANT(FINAL) SO THEY CANNOT BE CHANGED ONCE DECLARE.
    // ENUM CAN ONLY BE PUBLIC AND DEFAULT
    // ENUM CAN NOT BE INHERITED (cannot use extends keyword to created inheritance)
    // ENUM CAN HAVE CONSTRUCTOR
    // ENUM CAN BE DECLARED WITHIN A CLASS (INNER ENUM)
    // ENUM VARIABLES FOLLOW THESE DECLARATION CONVENTIONS: CAPS, ALPHABETIC, ONE PER LINE
    // ENUM IS BEST USE WHEN THE VARIABLE NAME AND THE VALUE IT IS WILL BE THE SAME -- EX: SMALL = small
    // NOTE: ENUM RETURN ENUM DATATYPE NOT STRING

    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY


}
